version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: resort
      POSTGRES_USER: resort
      POSTGRES_PASSWORD: resort
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    env_file:
      - token.env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

volumes:
  pgdata:
