# Generated by Django 5.2.11 on 2026-02-08 11:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('HOUSE', 'House'), ('VERANDA', 'Veranda'), ('GAZEBO', 'Gazebo')], default='HOUSE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_min', models.PositiveSmallIntegerField(default=1)),
                ('capacity_max', models.PositiveSmallIntegerField(default=1)),
                ('base_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted phone',
                'verbose_name_plural': 'Blacklisted phones',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='accommodations/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.accommodation')),
            ],
            options={
                'verbose_name': 'Accommodation image',
                'verbose_name_plural': 'Accommodation images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accommodation')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.amenity')),
            ],
            options={
                'verbose_name': 'Accommodation amenity',
                'verbose_name_plural': 'Accommodation amenities',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenities',
            field=models.ManyToManyField(related_name='accommodations', through='main.AccommodationAmenity', to='main.amenity'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='NEW', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('WEEKEND', 'Weekend'), ('PERIOD', 'Period')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='main.accommodation')),
            ],
            options={
                'verbose_name': 'Price rule',
                'verbose_name_plural': 'Price rules',
            },
        ),
        migrations.AddConstraint(
            model_name='accommodationamenity',
            constraint=models.UniqueConstraint(fields=('accommodation', 'amenity'), name='uniq_accommodation_amenity'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['accommodation', 'check_in', 'check_out'], name='idx_booking_dates'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'created_at'], name='idx_booking_user_created'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_in__lt', models.F('check_out'))), name='booking_check_in_before_check_out'),
        ),
        migrations.AddIndex(
            model_name='pricerule',
            index=models.Index(fields=['accommodation', 'kind', 'is_active'], name='idx_price_rule_kind'),
        ),
        migrations.AddIndex(
            model_name='pricerule',
            index=models.Index(fields=['accommodation', 'date_from', 'date_to'], name='idx_price_rule_dates'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_from__isnull', False), ('date_to__isnull', False), ('kind', 'PERIOD')), models.Q(('date_from__isnull', True), ('date_to__isnull', True), ('kind__in', ['WEEKDAY', 'WEEKEND'])), _connector='OR'), name='price_rule_dates_by_kind'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__lte', models.F('date_to')), models.Q(('date_from__isnull', True), ('date_to__isnull', True)), _connector='OR'), name='price_rule_valid_range'),
        ),
    ]
